version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    restart: on-failure
    ports:
      - ${PG_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
