  CREATE TABLE  IF NOT EXISTS users(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(60),
    first_name VARCHAR(30),
    last_name VARCHAR(30),
    avatar VARCHAR(60),
    UNIQUE (email, first_name, last_name, avatar)
);

CREATE INDEX IF NOT EXISTS  users_full_name_idx ON users (first_name, last_name);

CREATE INDEX IF NOT EXISTS  users_last_name_idx ON users(last_name);

